// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sftp} from '../models';
import {mysql} from '../models';
import {profiles} from '../models';
import {session} from '../models';
import {context} from '../models';
import {metrics} from '../models';
import {transfer} from '../models';

export function CredentialsDelete(arg1:string):Promise<void>;

export function CredentialsSetPassword(arg1:string,arg2:string):Promise<void>;

export function CredentialsSetPrivateKeyPassphrase(arg1:string,arg2:string):Promise<void>;

export function DialogOpenFile(arg1:string):Promise<string>;

export function DialogSaveFile(arg1:string,arg2:string):Promise<string>;

export function FilesList(arg1:string,arg2:string):Promise<Array<sftp.FileEntry>>;

export function FilesMkdir(arg1:string,arg2:string):Promise<void>;

export function FilesRemove(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function FilesRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FilesStat(arg1:string,arg2:string):Promise<sftp.FileEntry>;

export function HostKeyRespond(arg1:string,arg2:boolean):Promise<void>;

export function MySQLConnect(arg1:string):Promise<mysql.Status>;

export function MySQLCreateDatabase(arg1:string,arg2:string):Promise<void>;

export function MySQLCredentialsDelete(arg1:string):Promise<void>;

export function MySQLCredentialsSetPassword(arg1:string,arg2:string):Promise<void>;

export function MySQLDisconnect(arg1:string):Promise<void>;

export function MySQLDropDatabase(arg1:string,arg2:string):Promise<void>;

export function MySQLDropTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MySQLListDatabases(arg1:string):Promise<Array<string>>;

export function MySQLListTables(arg1:string,arg2:string):Promise<Array<string>>;

export function MySQLPreviewTable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<mysql.PreviewResult>;

export function MySQLProfilesDelete(arg1:string):Promise<void>;

export function MySQLProfilesList():Promise<Array<mysql.Profile>>;

export function MySQLProfilesSave(arg1:mysql.Profile):Promise<string>;

export function MySQLQuery(arg1:string,arg2:string,arg3:string):Promise<mysql.QueryResult>;

export function MySQLStatus(arg1:string):Promise<mysql.Status>;

export function MySQLTableSchema(arg1:string,arg2:string,arg3:string):Promise<Array<mysql.Column>>;

export function ProfilesDelete(arg1:string):Promise<void>;

export function ProfilesList():Promise<Array<profiles.Profile>>;

export function ProfilesSave(arg1:profiles.Profile):Promise<string>;

export function SessionConnect(arg1:string):Promise<string>;

export function SessionDisconnect(arg1:string):Promise<void>;

export function SessionStatus(arg1:string):Promise<session.Status>;

export function Startup(arg1:context.Context):Promise<void>;

export function SystemStats():Promise<metrics.Stats>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalOpen(arg1:string,arg2:number,arg3:number):Promise<string>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function TransferCancel(arg1:string):Promise<void>;

export function TransferDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TransferListTasks():Promise<Array<transfer.Task>>;

export function TransferUpload(arg1:string,arg2:string,arg3:string):Promise<string>;
