// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CredentialsDelete(arg1) {
  return window['go']['app']['App']['CredentialsDelete'](arg1);
}

export function CredentialsSetPassword(arg1, arg2) {
  return window['go']['app']['App']['CredentialsSetPassword'](arg1, arg2);
}

export function CredentialsSetPrivateKeyPassphrase(arg1, arg2) {
  return window['go']['app']['App']['CredentialsSetPrivateKeyPassphrase'](arg1, arg2);
}

export function DialogOpenFile(arg1) {
  return window['go']['app']['App']['DialogOpenFile'](arg1);
}

export function DialogSaveFile(arg1, arg2) {
  return window['go']['app']['App']['DialogSaveFile'](arg1, arg2);
}

export function FilesList(arg1, arg2) {
  return window['go']['app']['App']['FilesList'](arg1, arg2);
}

export function FilesMkdir(arg1, arg2) {
  return window['go']['app']['App']['FilesMkdir'](arg1, arg2);
}

export function FilesRemove(arg1, arg2, arg3) {
  return window['go']['app']['App']['FilesRemove'](arg1, arg2, arg3);
}

export function FilesRename(arg1, arg2, arg3) {
  return window['go']['app']['App']['FilesRename'](arg1, arg2, arg3);
}

export function FilesStat(arg1, arg2) {
  return window['go']['app']['App']['FilesStat'](arg1, arg2);
}

export function HostKeyRespond(arg1, arg2) {
  return window['go']['app']['App']['HostKeyRespond'](arg1, arg2);
}

export function MySQLConnect(arg1) {
  return window['go']['app']['App']['MySQLConnect'](arg1);
}

export function MySQLCreateDatabase(arg1, arg2) {
  return window['go']['app']['App']['MySQLCreateDatabase'](arg1, arg2);
}

export function MySQLCredentialsDelete(arg1) {
  return window['go']['app']['App']['MySQLCredentialsDelete'](arg1);
}

export function MySQLCredentialsSetPassword(arg1, arg2) {
  return window['go']['app']['App']['MySQLCredentialsSetPassword'](arg1, arg2);
}

export function MySQLDisconnect(arg1) {
  return window['go']['app']['App']['MySQLDisconnect'](arg1);
}

export function MySQLDropDatabase(arg1, arg2) {
  return window['go']['app']['App']['MySQLDropDatabase'](arg1, arg2);
}

export function MySQLDropTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLDropTable'](arg1, arg2, arg3);
}

export function MySQLListDatabases(arg1) {
  return window['go']['app']['App']['MySQLListDatabases'](arg1);
}

export function MySQLListTables(arg1, arg2) {
  return window['go']['app']['App']['MySQLListTables'](arg1, arg2);
}

export function MySQLPreviewTable(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['MySQLPreviewTable'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function MySQLProfilesDelete(arg1) {
  return window['go']['app']['App']['MySQLProfilesDelete'](arg1);
}

export function MySQLProfilesList() {
  return window['go']['app']['App']['MySQLProfilesList']();
}

export function MySQLProfilesSave(arg1) {
  return window['go']['app']['App']['MySQLProfilesSave'](arg1);
}

export function MySQLQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLQuery'](arg1, arg2, arg3);
}

export function MySQLStatus(arg1) {
  return window['go']['app']['App']['MySQLStatus'](arg1);
}

export function MySQLTableSchema(arg1, arg2, arg3) {
  return window['go']['app']['App']['MySQLTableSchema'](arg1, arg2, arg3);
}

export function ProfilesDelete(arg1) {
  return window['go']['app']['App']['ProfilesDelete'](arg1);
}

export function ProfilesList() {
  return window['go']['app']['App']['ProfilesList']();
}

export function ProfilesSave(arg1) {
  return window['go']['app']['App']['ProfilesSave'](arg1);
}

export function SessionConnect(arg1) {
  return window['go']['app']['App']['SessionConnect'](arg1);
}

export function SessionDisconnect(arg1) {
  return window['go']['app']['App']['SessionDisconnect'](arg1);
}

export function SessionStatus(arg1) {
  return window['go']['app']['App']['SessionStatus'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SystemStats() {
  return window['go']['app']['App']['SystemStats']();
}

export function TerminalClose(arg1) {
  return window['go']['app']['App']['TerminalClose'](arg1);
}

export function TerminalOpen(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalOpen'](arg1, arg2, arg3);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['app']['App']['TerminalWrite'](arg1, arg2);
}

export function TransferCancel(arg1) {
  return window['go']['app']['App']['TransferCancel'](arg1);
}

export function TransferDownload(arg1, arg2, arg3) {
  return window['go']['app']['App']['TransferDownload'](arg1, arg2, arg3);
}

export function TransferListTasks() {
  return window['go']['app']['App']['TransferListTasks']();
}

export function TransferUpload(arg1, arg2, arg3) {
  return window['go']['app']['App']['TransferUpload'](arg1, arg2, arg3);
}
